### ISSUE TITLE
FireOS app scheme detection failed

### ISSUE THREAD

**Issue by azn1viet** [ohh2ahh/AppAvailability#21]
Adobe Acrobat reader: Can't detect scheme for FireOS while native Android can. Not sure if it's affected to SS or any other devices or its variant Android powered.

**Comment by ohh2ahh** [comment]
Hi @azn1viet 
I'm afraid I can't help you with your problem because I'm not familiar with Fire OS and the plugin doesn't support it either. I leave the issue at least open and hope anybody else can help you.

**Comment by ohh2ahh** [comment]
Supplement:
I assume that the plugin doesn't even get loaded on Amazon Fire OS because of the missing `<platform name="amazon-fireos">` tag in `plugin.xml`. Something like the following code should add the plugin to Amazon Fire OS (not tested!). You can get more information on the [Amazon Fire OS plugin documentation](http://cordova.apache.org/docs/en/5.0.0/guide_platforms_amazonfireos_plugin.md.html#Amazon%20Fire%20OS%20Plugins).

```xml
<!-- Fire OS -->
<platform name="amazon-fireos">
    <config-file target="config.xml" parent="/*">
        <feature name="AppAvailability">
            <param name="android-package" value="com.ohh2ahh.appavailability.AppAvailability" />
        </feature>
    </config-file>
    <source-file src="src/android/AppAvailability.java" target-dir="src/com/ohh2ahh/appavailability/" />
</platform>
```
